[package]
name = "river/seeko"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
Zone = "mattschrubb/zoneplus@3.2.0"
Reflex = "littensy/reflex@4.3.1"
ReactReflex = "littensy/react-reflex@0.3.5"

[server-dependencies]
Lapis = "nezuo/lapis@0.3.1"
